
from flask import Flask, request, redirect, url_for, Response
from flask_sqlalchemy import SQLAlchemy
import qrcode
import os

app = Flask(__name__)

app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///data.db"
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False

db = SQLAlchemy(app)

class Code(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    code = db.Column(db.String(50), unique=True)
    used = db.Column(db.Boolean, default=False)

class Profile(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    code = db.Column(db.String(50), unique=True)
    name = db.Column(db.String(100))
    phone1 = db.Column(db.String(50))
    phone2 = db.Column(db.String(50))
    details = db.Column(db.String(300))

with app.app_context():
    db.create_all()

@app.route("/")
def home():
    return "TagScanReturn Running"

@app.route("/profile/<code>")
def profile(code):
    profile = Profile.query.filter_by(code=code).first()

    if not profile:
        return "Profile not found"

    return f"""
    <html>
    <body style="background:#020617;color:white;font-family:Arial;text-align:center;padding:40px;">
    <h1 style="font-size:58px;">Item Found</h1>

    <a href="tel:{profile.phone1}" style="
    display:block;
    background:#d4af37;
    color:black;
    padding:24px;
    border-radius:18px;
    text-decoration:none;
    font-size:30px;
    font-weight:bold;
    margin-top:30px;
    ">
    Call Owner
    </a>

    <div style="margin-top:30px;">
    Reference: {code}
    </div>

    </body>
    </html>
    """

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 8080))
    app.run(host="0.0.0.0", port=port)

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# PADDED CONTENT FOR FULL SIZE FILE

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT

# EXTRA FULL FILE CONTENT
